language: python
cache:
  pip: true
  directories:
  - "$HOME/.cache/pre-commit"
jobs:
  include:
  - python: '3.7'
  - python: '3.8'
  - python: '3.9'
  - python: '3.10'
    env: PRE_COMMIT=1
  fast_finish: true
dist: bionic
os: linux
install:
- if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then pip install -U importlib_metadata;
  fi
- pip install coverage coveralls
- test ! "$PRE_COMMIT" || pip install pre-commit
- pip install "mypy>=0.782"
- pip install -e .
script:
- test ! "$PRE_COMMIT" || pre-commit run --all-files
- mypy --python-version $TRAVIS_PYTHON_VERSION pysyncthru
- coverage run --source=pysyncthru setup.py test
after_success:
- coverage report
- coveralls
before_deploy:
- git config --local user.name "nielstron"
- export TRAVIS_TAG=release-$(cat setup.py | grep version= | cut -d "\"" -f 2)
- git tag $TRAVIS_TAG || echo "Tag already exists"
deploy:
  - provider: pypi
    on:
      branch: master
      python: '3.10'
    skip_existing: true
    username: __token__
    password:
      secure: fd8zSXq/kdNFLoYrfbc4FSIjBMULrlvEIsp0m9miAjconugsnOsigs6q5nJ676105qMkhQCs0fsp24zE4RpW6pabAO433eGZE5i3CbiOqzUTSy6xguTLM+Jk7mLBW1W6V2SmZa9cs1Zilg5PjIsErPBHo4xQudcBS9j8wbPrtivPd3sqEzsPVaBFp0o+3fogJjl9wD4KdhB1382Lg3s9TybUJ2/k9SrB+5dxMp/IyqeuBupnPHscCP5CnNfsu3IcjVLES053Hm+/5sAXSXiKDfe6ZH9Zzx845HelTvuXXNXbJjJx0eJS02bTe8i2uaBNmCCfpNOKoNm2BC9IaJ2Ku0rGnwUz8hgS7iHrRMHeEpSczFnltRaUwheH4Su9SVAiVyOsVmlAHnKk7tpWoi42Tzj6ImKUMWXrwaypDAALQM5uSu948AcpaTXZwOsGQPjPdnlw+vjraXXzqo4Qrh52QsZ6we5CLWesdVyd1hlfUuD0rwmfqmF9/KtBgfCYR3A78kG2e94rhUrvC0Ybho94k+2uISTfhbAktH+uFjV7gGhT1e+fHrEOXQ3SfY7zA25QkqjO31n8Ze242sYgXdJtu6cdupSkkLAXlXl/+mAuTQiRCWNOizE6O7Nyx8zNdVj7LtC6EsmABdrGYxN8wQ2Mvtr9VF6Ksp2OnqBbnTfVs/Y=
  - provider: releases
    cleanup: true
    overwrite: false
    on:
      branch: master
      python: '3.10'
      condition: "$TRAVIS_EVENT_TYPE = push"
    token:
      secure: UCdkdIOHZjSU/H6jLxEyiobJ4D44PnfSZE96qMaci1f8oVmYlq1Y9b+tfqD92ZeuMD9YwcOu5T106IKEtxJu8WUii1H8cDHN7ul1fvUvQan5b6o90Df+vLh3c3coj38lwDw4kxP5LsOCERMZ4OA5kM5sh11YiVhyYNyOYlBChFUeEUMRQkR3uu7pgGPEu7cZx7duRdr/3G3i0HKQUyHN3HRuqWQhQvhHgdrvUhEupc7KGsrn7KfQx/zPrCHZJZ1/wRvmGG/Yo8W0ZHXemWbubwI83Ho0VMdDKH2Nj+uNv+bZwGImGbhrG+SB7RwpynG8whKQCc5Mphr5r6LzOi6JbAMxJeIH/J/JsyZwe65EDcjPBKMuyrv6NDrmPiPmceLAN7idqEdw5J5NMcw9yhdMTxJNsUgSnSsHhaMW78R23MM/76jU3cew6D9d21h8aw1trcoOcJ0/h0q43OuSZ/uH045U4wMWD2mqEP94qdUg9vpkiw2dJ9FHs0F3kjfAze/m8VUQbhXxkXKvFBv/dcy/g6iG9lBYcXSOV+TFScuajTVRODDohN02OsQIqFt/5tUxDLmRzeJAPvOW7E7dxoeRfOj6l/6DIZ4SUY9vdXPYEqxbN27JE2nTPE6M6fGNRm6YfBRWL/ij0Zs5U+Ww6uS6c9rsXelXcZMqCFodwVbKlhE=
