language: python

matrix:
  include:
  - python: "3.4"
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
    dist: xenial
    sudo: required

  fast_finish: true

install: pip install -U tox

script: tox
